### ISSUE TITLE
Remove Redis requirement

### ISSUE THREAD

**Issue by sbordeyne** [jyotirmoy-paul/cached_build_runner#15]
This package uses redis as a backend for caching.

The primary purpose of this package is to speed up builds while in a CI (so constrained environment) or locally (on which redis is probably not available)

I don't see a real world use case of having redis, which adds an unnecessary dependency to the package.

**Comment by tenhobi** [comment]
should be easy to do https://github.com/netglade/cached_build_runner/blob/0ab5a3bc0dca40073575be31b68c403b5356a62c/lib/commands/initializer.dart#L24-L26

but we will triage whether we want to remove Redis completely since right now, it can be configured:

> 'Use redis database, if installed on the system. Using redis allows multiple instance access. Ideal for usage in pipelines. Default implementation uses a file system storage (hive), which is idea for usage in local systems.'

**Comment by sbordeyne** [comment]
I'm using github actions as my CI tool, and its caching system relies on the filesystem. I don't know about other CIs (travis, gitlab, jenkins), but I don't think many of them support redis as a caching backend. Maybe jenkins can work with it since it's self hosted, or a github actions self hosted runner, but for managed solutions it's more ambiguous.

My bet would be to fork the package into one with redis as a backend and one with file storage as a backend so that the user can choose the more suitable option.
