### ISSUE TITLE
cached_build_runner watch exits after completing

### ISSUE THREAD

**Issue by matthewtsmith** [jyotirmoy-paul/cached_build_runner#2]
Hello, I'm attempting to try this package for one of my projects. I regularly use `flutter pub run build_runner watch` so that the code generation kicks off as I change things.

When I run `flutter pub run cached_build_runner watch` the code is generated and then it exits. 

This tool should mimic the behavior `build_runner watch`

**Comment by jyotirmoy-paul** [comment]
Hi Matthew, thanks for your feedback. I got it, will work on this feature, and make it more similar to how build_runner works.

**Comment by jyotirmoy-paul** [comment]
@matthewtsmith Please try the latest `cached_build_runner` version `0.0.5` the watch functionality has been added. Thanks!

**Comment by neiljaywarner** [comment]
@jyotirmoy-paul  awesome!  Is there anything i'm missing or is this the greatest thing since sliced bread? :)

**Comment by jyotirmoy-paul** [comment]
@neiljaywarner I think you are all set, let me know if you find any bugs or further enhancements :)
