### ISSUE TITLE
Adding new files is not detected

### ISSUE THREAD

**Issue by simplenotezy** [jyotirmoy-paul/cached_build_runner#7]
Thanks a lot for some super awesome job on this package - it's a really needed package, since in bigger flutter projects the build runner is a serious development productivity decreaser.

I have noticed, after using it for a little while, that if we add new files, we have to use the normal build_runner. It would be nice if it could automatically detect new files based on the `build.yaml` watch rules and then reload accordingly.

**Comment by jyotirmoy-paul** [comment]
Thanks for your kind words :)

New files should have been detected on it's own, can you please share details if possible? Just a small reproducible codebase would be of great help, you can explain briefly here as well. Thanks!

**Comment by simplenotezy** [comment]
@jyotirmoy-paul Thanks! I will do that next time I happens and report back here.

Until then, a possible reason could be that in our build.yaml we tend to always specific which files we wish to generate for each package, e.g.:

```yaml
targets:
  $default:
    builders:
      mobx_codegen:mobx_generator:
        generate_for:
          - lib/legacy/**/*.dart
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/flutter_splash_screen.dart
          - lib/playground.dart
          - lib/**/presentation/**/*.dart
          - lib/**/presentation/*.dart
          - lib/common/widgets/loading_screen.dart
      auto_route_generator:auto_router_generator:
        generate_for: [ lib/features/router/router.dart ]
      json_serializable:
        generate_for:
          - lib/common/domain/*.dart
          - lib/**/domain/*.dart
        options:
          explicit_to_json: true

**Comment by simplenotezy** [comment]
It works 🎉, but it just took longer time than expected, and no progress bar indicating it was building.

I think the runner needs more information about the currently running process; e.g. a progress-bar, or something similar, because it's difficult to decode whether or not it's currently doing something or not.

**Comment by jyotirmoy-paul** [comment]
Yes correct, as I explained [here](https://github.com/jyotirmoy-paul/cached_build_runner/issues/9#issuecomment-1563729619) we should print logs while the underlying build_runner is building.

**Comment by simplenotezy** [comment]
Sounds good! 😊
