### ISSUE TITLE
Does it work on freezed classes?

### ISSUE THREAD

**Issue by simplenotezy** [jyotirmoy-paul/cached_build_runner#8]
I noticed that nothing happens if I update a freezed only class - not sure why.

If I add a new property to a freezed class it does not seem to regenerate.

Update:
--

So it appears it's only checking `.g.dart` files, not `.freezed.dart` - could that be true?

**Comment by jyotirmoy-paul** [comment]
Yes it only checks for the `dart` files for now, the process of figuring out which classes needs generation is wrong, I am working on improving it.

**Comment by hm-tamim** [comment]
Any update on it?

**Comment by petrnymsa** [comment]
@jyotirmoy-paul  Can we help with you on this? We would like to use this but in our project we use `.freezed` and other suffixes.

**Comment by sbordeyne** [comment]
Hello, can it also include `.chopper.dart` as well ?
