### ISSUE TITLE
Add --verbose flag

### ISSUE THREAD

**Issue by simplenotezy** [jyotirmoy-paul/cached_build_runner#9]
It would be nice if you could run with --verbose flag, so you could see the verbose ouput from the underlying build_runner and perhaps any other relevant debugging information

**Comment by jyotirmoy-paul** [comment]
Hi @simplenotezy by default the cached_build_runner is verbose, in fact to quieten it you have to use the `--quiet` (or, `-q`) flag.

But there is no log while the underlying build_runner is running, it logs the output once it's done, so during the process nothing is printed. I have noted that, will work on it, thanks.

**Comment by simplenotezy** [comment]
I thought the same initially actually. However, if you compare it with the verbose mode of the normal build runner it's quite different
